---
title: "16S rRNA analysis"
author: "Edmond Berne"
date: "2024-08-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading_packages, include=FALSE}
#.libPaths("/home/edmond/R/x86_64-pc-linux-gnu-library/4.3") # path to the R libraries (personnal environnement)
library(phyloseq)
library(ampvis2)
library(ggplot2)
library(vegan)
library(dplyr)
library(rprojroot)
library(ggpubr)
library(plotly)
library(vegan)
# format the html output
library(kableExtra)
```


```{r set the working directory, include=FALSE}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) # set the working directory to the location of this script
```

```{r loading data, include = FALSE}

# Import data
df_feature = read.csv("ressources/data/otu_table_merged_transpose.csv")
df_tax = read.csv("ressources/data/tax_table_merged.csv", sep = ";")
df_meta = read.csv("ressources/data/metadata1.csv")

df_feature = df_feature %>%
  tibble::column_to_rownames("ASV") # format the table for phyloseq

df_tax = df_tax %>% 
  tibble::column_to_rownames("ASV")

df_meta = df_meta %>% 
  tibble::column_to_rownames("Sample_ID") 

otu_mat = as.matrix(df_feature) # format again
tax_mat = as.matrix(df_tax)
OTU = otu_table(otu_mat, taxa_are_rows = TRUE)
TAX = tax_table(tax_mat)
samples = sample_data(df_meta)
physeq = phyloseq(OTU, TAX, samples)
physeq = subset_taxa(physeq, Kingdom == "Bacteria") # remove non-bacterial sequences
physeq = subset_taxa(physeq, Family != "mitochondria") # remove mitochondria sequences
physeq = subset_taxa(physeq, Family != "chloroplast" ) # remove chloroplaste sequences

# the line to filter the data to keep only the control samples
physeq = subset_samples(physeq, Treatment == "Water")
physeq@sam_data$Week = as.factor(physeq@sam_data$Week)
ampvis_data = amp_load(physeq)
saveRDS(physeq, file = "output/physeq_ctrl.rds")
```


### Rarefaction curves by treatment condition
```{r rarefactioncurve, include = FALSE}
Rarecurve = function(data, col, type) { 
  cat("Creating rarefaction curve for ", type, " samples\n")
  p3 = amp_rarecurve(data, color_by = col, stepsize = 100, facet_by = "Treatment")
  p3 = p3 + theme(axis.text = element_text(size = 14), 
             axis.title = element_text(size = 20), 
             legend.text = element_text(size = 15), 
             legend.title = element_text(size = 15)) +
    theme(axis.text = element_text(angle = 0, hjust = 0.5, size = 14),
          axis.title = element_text(size = 20), 
          axis.text.y = element_text(angle = 0),
          strip.text = element_text(size = 20),
          legend.text = element_text(size = 18),  # Agrandir le texte du titre de chaque facette + # Mettre les graduations à l'horizontale et les agrandir
           legend.title = element_text(size = 20))+
    labs(y = "Number of ASVs")+
    geom_line(linewidth = 1.5)
  cat("Saving the plot\n")
  ggsave(paste0("output/rarefaction_curve_control_", type ,".png"), width = 10, height = 10)
  return(p3)
}
ampvis_data$metadata$Week = ifelse(ampvis_data$metadata$Week == 2, "week 2",
                                  ifelse(ampvis_data$metadata$Week == 4, "week 4", "week 5"
                                  ))
p1 = Rarecurve(data = ampvis_data, col = "Week", type = "Rhizoplane")
```



```{r rarefaction, include = FALSE}
rarefied_physeq_list = list() # a list to store the rarefied phyloseq objects
for (i in 1:100) {
  rarefied_physeq = rarefy_even_depth(physeq, sample.size = 0.9 * min(sample_sums(physeq)), rngseed = i)
  rarefied_physeq_list[[i]] <- rarefied_physeq
  cat("Loop number: \r", i, "out of 100")
}
otu_tables = lapply(rarefied_physeq_list, function(x) otu_table(x)) # regroup all the otu_tables in a list

cat("All the rarefied phyloseq objects have been created")
cat("Converting otu_tables to dataframes...")

for (i in 1:length(otu_tables)) { # convert all the otu_tables to dataframes
  otu_tables[[i]] = as.data.frame(otu_tables[[i]])
  otu_tables[[i]]$ASV = rownames(otu_tables[[i]])
  cat("Loop number: \r", i, "out of 100")
}

cat("Dataframes created")
cat("Concatenating dataframes...")

df_rare = as.data.frame(otu_tables[[1]]) # create a dataframe with the first otu_table for later
for (i in 2:length(otu_tables)) { # Concatenate all the dataframes vertically
  df_rare = rbind(df_rare, as.data.frame(otu_tables[[i]]))
  cat("Loop number: \r", i, "out of 100")
}

cat("Rarefied dataframe created")
cat("Calculating mean and median...")

# Regroup rows by NAME and calculate the mean and median
df_rare_mean = df_rare %>% group_by(ASV) %>% summarise(across(everything(), list(mean = mean)))
df_rare_median = df_rare %>% group_by(ASV) %>% summarise(across(everything(), list(median = median)))

names(df_rare_mean) = sub("_mean", "", names(df_rare_mean)) # Remove mean and median to column names
names(df_rare_median) = sub("_median", "", names(df_rare_median))

df_rare_mean <- df_rare_mean %>%
  tibble::column_to_rownames("ASV")

df_rare_median <- df_rare_median %>%
  tibble::column_to_rownames("ASV")

df_rare_mean = otu_table(df_rare_mean, taxa_are_rows = TRUE)
df_rare_median = otu_table(df_rare_median, taxa_are_rows = TRUE)
Rarefied_physeq_mean = phyloseq(df_rare_mean, TAX, samples) # create another phyloseq object with rarefied data as OTU table
Rarefied_physeq_median = phyloseq(df_rare_median, TAX, samples)

otu_data = round(otu_table(Rarefied_physeq_mean))
# In case where we have float number in mean (for richness), we round the number to have an integer
Rarefied_physeq_mean_rounded <- phyloseq(otu_data, TAX, samples)

saveRDS(Rarefied_physeq_mean_rounded, file = "ressources/RDS/Rarefied_physeq_mean_rounded.rds")
saveRDS(Rarefied_physeq_median, file = "ressources/RDS/Rarefied_physeq_median.rds")
saveRDS(df_rare_mean, file = "ressources/RDS/df_rare_mean.rds")
```

### Descriptive statistics 
    *(based on nonchim reads)*
```{r descriptive statistics, include = TRUE}
reads_data = read.csv("ressources/track.txt", sep = "\t")
number_ASV = colSums(df_feature)
reads_data = cbind(reads_data, df_meta) # add metadata to the reads data
reads_data$ASV = number_ASV
table = reads_data %>% 
    filter(Treatment == "Water") %>% # remove this line to get data for all the samples
    group_by() %>% 
    summarise(mean_reads = mean(nonchim), median_reads = median(nonchim), reads_number = sum(nonchim),
                                min_reads = min(nonchim), max_reads = max(nonchim), ASV_sum = sum(ASV), samples = n())
table = as.data.frame(table)

table %>%
  kable("html", caption = "Descriptive Statistics") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = F)
```


### Loading data
```{r load rarefied data, include = TRUE}
physeq_rare_mean = readRDS("output/df_rare_mean.rds")
physeq_rare_median = readRDS("output/Rarefied_physeq_median.rds")
physeq_rare_mean_rounded = readRDS("output/Rarefied_physeq_mean_rounded.rds")
```


### Alpha diversity

```{r alpha diversity function, include = FALSE}

alpha_box_plot = function(data, x_var,y_var, col, comparizon, nb_test, name){
  
  symnum = list(cutpoints = c(0, 0.0001/nb_test, 0.001/nb_test, 0.01/nb_test, 0.05/nb_test, Inf), symbols = c("****", "***", "**", "*", "ns"))
  p = ggplot(data = data, aes_string(x = x_var, y = y_var, color = col))+
    geom_boxplot() +
    facet_grid(~ Week, scales = "free") + # organise the plot by week
    theme(axis.text.x = element_text(hjust = 1, size = 20, angle = 45),  
          axis.text.y = element_text(size = 20),  
          legend.title = element_text(size = 20),
          legend.text = element_text(size = 18),
          plot.title = element_text(size = 20, face = "bold", hjust = 0.5),
          axis.title.x = element_text(size = 24),  
          axis.title.y = element_text(size = 24),
          strip.text = element_text(size = 15)) +  
    ylim(c(min(data[[y_var]]) - 0.1 * min(data[[y_var]]) , max(data[[y_var]]) + 0.1 *max(data[[y_var]]))) +
    labs(x = "Sub sample", y = paste0(y_var, " diversity"))+
    stat_compare_means(comparisons = comparizon, symnum.args = symnum, label = "p.signif", size = 10 )
   ggsave(paste0("output/alpha_diversity_",name ,"_", y_var, ".png"), plot = p, width = 25, height = 15, units = "cm")
   return(p)
}

```

```{r alpha diversity_loading data, include = FALSE}
alpha_div = estimate_richness(physeq_rare_mean_rounded, measures = c("Shannon", "Chao1")) # compute alpha diversity
alpha_div = cbind(alpha_div, physeq_rare_mean_rounded@sam_data) # add the factor to the new table
alpha_div$Week = ifelse(alpha_div$Week == 2, "2weeks",
                        ifelse(alpha_div$Week == 4, "4weeks", "5weeks"
                        ))
comparison = list(c("Watered", "Drought")) # change this according to the variable you want to compare
nb_test = 2 # for Bonferonni correction
```

```{r alpha diversity_loading plots, include = FALSE}
p2 = alpha_box_plot(data = alpha_div, x_var = "Irrigation", y_var = "Shannon", col = "Irrigation", comparizon = comparison , nb_test = nb_test, name = "control")
p3 = alpha_box_plot(data = alpha_div, x_var = "Irrigation", y_var = "Chao1", col = "Irrigation", comparizon = comparison , nb_test = nb_test, name = "control")
```

#### Shannon diversity
```{r alpha diversity_loading shannon, include = TRUE, fig.width=10, fig.height=8}
p2
```

#### Richness
```{r alpha diversity_loading richness, include = TRUE, fig.width=10, fig.height=8}
p3
```



### Beta diversity
```{r beta diversity Function, include = FALSE, fig.width=10, fig.height=8}
plot_pcoa = function(data, color, cluster, filename){
    list_output = list() # to return the plot and the beta diversity results
    print("Computing PCoA")
    physeq.ord_pcoa = ordinate(data, "PCoA", "bray")
    print("Plotting PCoA")
    p3 = plot_ordination(data, physeq.ord_pcoa, color=color,  
                  title="Beta diversity study using PCoA method (Bray-Curtis dissimilarity)") +
           geom_point(size = 3)+
          theme(axis.text = element_text(size = 15), axis.title = element_text(size = 25), 
                legend.text = element_text(size = 25), legend.title = element_text(size = 27))

    # add the elipse on the plot
    p3 = p3 + stat_ellipse(aes_(color = as.name(cluster), fill = as.name(cluster)), geom = "polygon", show.legend = T, linetype = "dashed", linewidth = 1, alpha = 0.1)+ 
     labs(color = "Groups", fill = "Groups")+
          scale_color_manual(values = c("Week 2 control" = "#F8766D", # change the color of the groups points
                                        "Week 4 drought" = "#B79F00", 
                                        "Week 4 control" = "#00BA38", 
                                        "Week 5 control" = "#F564E3", 
                                        "Week 5 drought" = "#619CFF")) +
          scale_fill_manual(values = c("Week 2 control" = "#F8766D", # change the color of the groups ellipse
                                       "Week 4 drought" = "#B79F00", 
                                       "Week 4 control" = "#00BA38", 
                                       "Week 5 control" = "#F564E3", 
                                       "Week 5 drought" = "#619CFF")) 
   
    ggsave(filename)
    list_output[[1]] = p3
    list_output[[2]] = physeq.ord_pcoa
    return(list_output)
}

```

```{r beta diversity PCoA plot, include = TRUE, fig.width=10, fig.height=8}

physeq_rare_mean_rounded@sam_data$Group = ifelse(physeq_rare_mean_rounded@sam_data$Group == "2Watered" , "Week 2 control",
                                                                 ifelse(physeq_rare_mean_rounded@sam_data$Group == "4Drought", "Week 4 drought", 
                                                                 ifelse(physeq_rare_mean_rounded@sam_data$Group == "4Watered", "Week 4 control",
                                                                 ifelse(physeq_rare_mean_rounded@sam_data$Group == "5Watered", "Week 5 control","Week 5 drought"))))

p4 = plot_pcoa(physeq_rare_mean_rounded, "Group", "Group", "output/PCoA_16S_rRNA_cluster.png")
saveRDS(p4[[2]], file = "output/physeq_ord_pcoa.rds")
```

```{r, include = TRUE}
p4[[1]]
```




