---
title: "16S rRNA analysis"
author: "Edmond Berne"
date: "2024-08-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading_packages, include=FALSE}
#.libPaths("/home/edmond/R/x86_64-pc-linux-gnu-library/4.3") # path to the R libraries (personnal environnement)
library(phyloseq)
library(ampvis2)
library(ggplot2)
library(vegan)
library(dplyr)
library(rprojroot)
library(ggpubr)
library(plotly)
library(vegan)
# format the html output
library(kableExtra)
```


```{r set the working directory, include=FALSE}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) # set the working directory to the location of this script
```

```{r loading data, include = FALSE}

# Import data
df_feature = read.csv("ressources/data/otu_table_merged_transpose.csv")
df_tax = read.csv("ressources/data/tax_table_merged.csv", sep = ";")
df_meta = read.csv("ressources/data/metadata1.csv")


df_feature = df_feature %>%
  tibble::column_to_rownames("ASV") # format the table for phyloseq

df_tax = df_tax %>% 
  tibble::column_to_rownames("ASV")

df_meta = df_meta %>% 
  tibble::column_to_rownames("Sample_ID") 

otu_mat = as.matrix(df_feature) # format again
tax_mat = as.matrix(df_tax)
OTU = otu_table(otu_mat, taxa_are_rows = TRUE)
TAX = tax_table(tax_mat)
samples = sample_data(df_meta)
physeq = phyloseq(OTU, TAX, samples)
physeq = subset_taxa(physeq, Kingdom == "Bacteria") # remove non-bacterial sequences
physeq = subset_taxa(physeq, Family != "Mitochondria" | Family == NA) # remove mitochondria sequences
physeq = subset_taxa(physeq, Class != "Chloroplast" ) # remove chloroplast sequences

# the line to filter the data to keep only the control samples
physeq = subset_samples(physeq, Treatment == "Water")
physeq@sam_data$Week = as.factor(physeq@sam_data$Week)
ampvis_data = amp_load(physeq)
physeq_f<-prune_taxa(taxa_sums(physeq)>0,physeq)
saveRDS(physeq_f, file = "output/physeq_ctrl.rds")
```


### Rarefaction curves by treatment condition
```{r rarefactioncurve, include = FALSE}
Rarecurve = function(data, col, type) { 
  cat("Creating rarefaction curve for ", type, " samples\n")
  p3 = amp_rarecurve(data, color_by = col, stepsize = 100, facet_by = "Treatment")
  p3 = p3 + theme(axis.text = element_text(size = 14), 
             axis.title = element_text(size = 20), 
             legend.text = element_text(size = 15), 
             legend.title = element_text(size = 15)) +
    theme(axis.text = element_text(angle = 0, hjust = 0.5, size = 14),
          axis.title = element_text(size = 20), 
          axis.text.y = element_text(angle = 0),
          strip.text = element_text(size = 20),
          legend.text = element_text(size = 18),  # Agrandir le texte du titre de chaque facette + # Mettre les graduations à l'horizontale et les agrandir
           legend.title = element_text(size = 20))+
    labs(y = "Number of ASVs")+
    geom_line(linewidth = 1.5)
  cat("Saving the plot\n")
  ggsave(paste0("output/rarefaction_curve_control_", type ,".png"), width = 10, height = 10)
  return(p3)
}
ampvis_data$metadata$Week = ifelse(ampvis_data$metadata$Week == 2, "week 2",
                                  ifelse(ampvis_data$metadata$Week == 4, "week 4", "week 5"
                                  ))
p1 = Rarecurve(data = ampvis_data, col = "Week", type = "Rhizoplane")
```



```{r rarefaction, include = FALSE}
rarefied_physeq_list = list() # a list to store the rarefied phyloseq objects
for (i in 1:100) {
  rarefied_physeq = rarefy_even_depth(physeq, sample.size = 0.9 * min(sample_sums(physeq)), rngseed = i)
  rarefied_physeq_list[[i]] <- rarefied_physeq
  cat("Loop number: \r", i, "out of 100")
}
otu_tables = lapply(rarefied_physeq_list, function(x) otu_table(x)) # regroup all the otu_tables in a list

cat("All the rarefied phyloseq objects have been created")
cat("Converting otu_tables to dataframes...")

for (i in 1:length(otu_tables)) { # convert all the otu_tables to dataframes
  otu_tables[[i]] = as.data.frame(otu_tables[[i]])
  otu_tables[[i]]$ASV = rownames(otu_tables[[i]])
  cat("Loop number: \r", i, "out of 100")
}

cat("Dataframes created")
cat("Concatenating dataframes...")

df_rare = as.data.frame(otu_tables[[1]]) # create a dataframe with the first otu_table for later
for (i in 2:length(otu_tables)) { # Concatenate all the dataframes vertically
  df_rare = rbind(df_rare, as.data.frame(otu_tables[[i]]))
  cat("Loop number: \r", i, "out of 100")
}

cat("Rarefied dataframe created")
cat("Calculating mean and median...")

# Regroup rows by NAME and calculate the mean and median
df_rare_mean = df_rare %>% group_by(ASV) %>% summarise(across(everything(), list(mean = mean)))
df_rare_median = df_rare %>% group_by(ASV) %>% summarise(across(everything(), list(median = median)))

names(df_rare_mean) = sub("_mean", "", names(df_rare_mean)) # Remove mean and median to column names
names(df_rare_median) = sub("_median", "", names(df_rare_median))

df_rare_mean <- df_rare_mean %>%
  tibble::column_to_rownames("ASV")

df_rare_median <- df_rare_median %>%
  tibble::column_to_rownames("ASV")

df_rare_mean = otu_table(df_rare_mean, taxa_are_rows = TRUE)
df_rare_median = otu_table(df_rare_median, taxa_are_rows = TRUE)
Rarefied_physeq_mean = phyloseq(df_rare_mean, TAX, samples) # create another phyloseq object with rarefied data as OTU table
Rarefied_physeq_median = phyloseq(df_rare_median, TAX, samples)

otu_data = round(otu_table(Rarefied_physeq_mean))
# In case where we have float number in mean (for richness), we round the number to have an integer
Rarefied_physeq_mean_rounded <- phyloseq(otu_data, TAX, samples)

saveRDS(Rarefied_physeq_mean_rounded, file = "ressources/RDS/Rarefied_physeq_mean_rounded.rds")
saveRDS(Rarefied_physeq_median, file = "ressources/RDS/Rarefied_physeq_median.rds")
saveRDS(df_rare_mean, file = "ressources/RDS/df_rare_mean.rds")
```

### Descriptive statistics 
    *(based on nonchim reads)*
```{r descriptive statistics, include = TRUE}
reads_data = read.csv("ressources/data/track.txt", sep = "\t")
number_ASV = colSums(df_feature)
reads_data = cbind(reads_data, df_meta) # add metadata to the reads data
reads_data$ASV = number_ASV
table = reads_data %>% 
    filter(Treatment == "Water") %>% # remove this line to get data for all the samples
    group_by() %>% 
    summarise(mean_reads = mean(nonchim), median_reads = median(nonchim), reads_number = sum(nonchim),
                                min_reads = min(nonchim), max_reads = max(nonchim), ASV_sum = sum(ASV), samples = n())
table = as.data.frame(table)

table %>%
  kable("html", caption = "Descriptive Statistics") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = F)
```


